---
name: ci
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: yaml-lint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: '.github/ci/yamllint.yml'
          yamllint_strict: true
