---
name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: yaml-lint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: '.github/ci/yamllint.yml'
          yamllint_strict: true
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Build
        run: |
          docker build .
          VPP_VERSION=$(docker run $(docker build -q . --target version))
          echo "VPP_VERSION=${VPP_VERSION}" >> $GITHUB_ENV
          TAG=v${VPP_VERSION/\~/-}
          echo "TAG=${TAG}" >> $GITHUB_ENV
          docker build -t ghcr.io/${{github.repository}}/vpp:${TAG} . --target vpp
          docker build -t ghcr.io/${{github.repository}}/vpp-dbg:${TAG} . --target vpp-dbg
          docker build -t ghcr.io/${{github.repository}}/vpp-api:${TAG} . --target vpp-api
      - name: Docker Push
        if: ${{steps.secrets.outputs.GHCR_TOKEN != '' && github.head_ref == ''}}
        run: |
          docker push ghcr.io/${{github.repository}}/vpp:${TAG}
          docker push ghcr.io/${{github.repository}}/vpp-dbg:${TAG}
          docker push ghcr.io/${{github.repository}}/vpp-api:${TAG}
      - name: Tag
        if: ${{steps.secrets.outputs.GHCR_TOKEN != '' && github.head_ref == ''}}
        id: tag
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.TAG }}
          tag_prefix: ""
